### ISSUE TITLE
sqs: ReceiveMessageRequest.messageSystemAttributeNames has no effect?

### ISSUE THREAD

**Issue by agavrilov76** [softwaremill/elasticmq#1004]
An attempt of replacing deprecated method `ReceiveMessageRequest.attributeNamesWithStrings("SentTimestamp")` with `ReceiveMessageRequest.messageSystemAttributeNames("SentTimestamp") `as suggested by the AWS SDK documentation doesn't seem to have any effect.  The system attribute is not returned when using messageSystemAttributeXXX method

**Comment by micossow** [comment]
fixed in `v1.6.2`
