### ISSUE TITLE
Using scala 3 version newer than the LTS release forces clients to do that as well.

### ISSUE THREAD

**Issue by Kreinoee** [softwaremill/elasticmq#1062]
So as this is a library, I would suggest sticking to the LTS version of scala 3, to make it available to as many projects as possible, without forcing them to upgrade there scala 3 version. 

I originally was, but got upgraded in version https://github.com/softwaremill/elasticmq/releases/tag/v1.6.1 via this PR: https://github.com/softwaremill/elasticmq/pull/992 

I created a draft PR for it, but I had a hard time getting the build to work on my box, and ran out of time for it. So the PR is not tested, and that why it's only a draft. 

https://github.com/softwaremill/elasticmq/pull/1061

**Comment by micossow** [comment]
Fixed in [v1.6.9](https://github.com/softwaremill/elasticmq/releases/tag/v1.6.9), thanks!
