### ISSUE TITLE
arm64 native docker image does not work on kernel with 16K page size

### ISSUE THREAD

**Issue by diegobfernandez** [softwaremill/elasticmq#1073]
I am running elastimq-native in docker and the containers immediatly exits with error `Failed to create main Isolate`.
My computer is a arm64 apple silicon running Asahi Linux. I've faced this issue with babashka and other Clojure tools that rely on GraavlVM.

This is a recurrent issue with software built with GraalVM since it defaults to the kernel page size of the host running the build.

The solution is to build with 64K page size which is compatible with all other officially supported ARM page sizes.

Here is the solution I proposed for all graalvm packages in nixpkgs: https://github.com/NixOS/nixpkgs/pull/269522.
Similar solution can be applied to build.sbt to allow usage in asahi linux and newer raspberry pi images.

This is an graalvm issue about this topic: https://github.com/oracle/graal/pull/5605#issuecomment-1364006130

**Comment by micossow** [comment]
Hi @diegobfernandez I created a branch with the param you suggested and it seems to built successfully. Can you verify if the image `softwaremill/elasticmq-native:1.6.10-RC1` works on your hardware?

**Comment by diegobfernandez** [comment]
Thanks a lot @micossow. I can confirm that `softwaremill/elasticmq-native:1.6.10-RC1` works on Asahi's 16K page size Linux.
Unfortunately I won't be able to test it on my Raspberry PI 5 in the next couple of months, but from past experiences it should work :crossed_fingers:

**Comment by micossow** [comment]
Thanks! The fix has been released.
