### ISSUE TITLE
Custom QueueUrlContext

### ISSUE THREAD

**Issue by mal** [softwaremill/elasticmq#117]
Currently when creating a queue the URL is always of the form `http://<host>/queue/<name>`. Originally I thought I could configure the `queue` part via the `context-path` setting, but that does not appear to be the case. Would it be possible to allow this [hardcoded](https://github.com/adamw/elasticmq/blob/80bc3978f943752143b4cc009902e0a638fd8b45/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L228) value to be customised?

This is also a request to be able to hit the URL generated with the custom `QueueUrlContext` too.

**Comment by adamw** [comment]
Sure, that should be a matter of a simple configuration option. However the addresses returned by SQS always contain queue (unless something changed?), hence the current behavior.

**Comment by mal** [comment]
Hmm, the queues I'm using on SQS are made up of `https;//<sqs-endpoint>/<aws-accound-id>/<queue-name>`. These are all on queues that live in the default region `us-east-1` and has dual working endpoints `queue.amazonaws.com` (legacy?) and `us-east-1.sqs.amazonaws.com`. Maybe it's a region inconsistency?

At any rate being able to change it in ElasticMQ would make for easier mocking as app code wouldn't have to distinguish between the global account ID used else where and the `queue` account it needs to use when in a mocked environment.

**Comment by adamw** [comment]
Ah, maybe something changed since I originally wrote that or it's indeed region-specific. Anyway, adding such a config option should be pretty straightforward.

**Comment by gpedic** [comment]
I would like to expand on this issue, AWS will actually allow you to omit the account id completely so both `https://<sqs-endpoint>/<aws-accound-id>/<queue-name>` and `https://<sqs-endpoint>/<queue-name>` will work while elasticmq always requires one to define the `QueueUrlContext` i.e. `queue`.

My code relies on being able to omit the account id at the moment so it would be great if elasticmq could simply accept requests without `QueueUrlContext` like `http://localhost:9324/<queue-name>` or simply alternatively rewrite them to `http://localhost:9324/queue/<queue-name>`.

Being able to remove `QueueUrlContext` completely via config for example by being able to define it as empty string could also be a simple solution.

**Comment by sashaaKr** [comment]
Hey there, 
any progress on this issue?

**Comment by micossow** [comment]
Hi, it's fixed in [1.3.13](https://github.com/softwaremill/elasticmq/releases/tag/v1.3.12)
You can now use both `http://<host>:<port>/queueName` and `http://<host>:<port>/[a-zA-Z0-9]+/queueName` urls to access the queue.
Also, the context path in config is now respected, respectively: `http://<host>:<port>/my-context/queueName` and `http://<host>:<port>/my-context/[a-zA-Z0-9]+/queueName`
