### ISSUE TITLE
 when using queue name to send messages get Invalid request: MissingQueryParamRejection(QueueName),

### ISSUE THREAD

**Issue by IdanFridman** [softwaremill/elasticmq#123]
While trying to send message to queue with ElasticMQ (embedded) I get this exception:

` Invalid request: MissingQueryParamRejection(QueueName)
`

this is how i send message to the queue: 
```
SendMessageRequest sendMsgRequest = new SendMessageRequest()
                    .withQueueUrl("dev-Test-Queue")
                    .withMessageBody(message);

```

create embedded queue:

```
   SQSRestServerBuilder
                .withPort(SQS_PORT)
                .withInterface("localhost")
                .start();
    }
```

init client:

```
 sqs = AmazonSQSClientBuilder.standard()
                .standard().withClientConfiguration(getClientConfiguration())
                .withCredentials(getCredentialsProvider())
                .withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration("http://localhost:8887", region))
                .build();
```
        
//create new queue:

```
    public String createQueue(String address, Map<String, String> attributes) {
        CreateQueueRequest createQueueRequest = new CreateQueueRequest("dev-Test-Queue");
        sqs.createQueue(createQueueRequest);
    }

```

the only way it works is if I send messages this way:

```
this is how i send message to the queue: 
SendMessageRequest sendMsgRequest = new SendMessageRequest()
                    .withQueueUrl("http://localhost:8887/queue/dev-Test-Queue")
                    .withMessageBody(message);
```

I have to write the full path "**http://localhost:8887/queue/dev-Test-Queue**" 
while using real SQS api mentioning only the queue name (**dev-Test-Queue**) is enough.

any idea how to over come this?
thanks.

**Comment by adamw** [comment]
I think the general contract is that for `queueUrl` you should use whatever a `CreateQueue`/`GetQueueUrl` call returns, without any assumptions on a specific form of the url?

But I might be wrong of course; if you'd find the appropriate place in the docs, let me know!

**Comment by IdanFridman** [comment]
@adamw When using SQS while sending messages I dont need to mention the ful queueUrl (e.g http://aws....:port/queue-name

using elasticMQ i must do that.

**Comment by adamw** [comment]
@IdanFridman I understand, but is that documented SQS behavior, or just happens to work and might break in the future?

**Comment by IdanFridman** [comment]
I couldnt find something on docs perhaps i didnt look deep enough. however on real sqs client i see this:

11:46:58.498 DEBUG c.a.request:1183 - Sending Request: POST https://sqs.eu-west-1.amazonaws.com /dev-Test-Queue Parameters: ({"Action":["ReceiveMessage"],"Version":["2012-11-05"],"AttributeName.1":["All"],"MessageAttributeName.1 .....

they adding the endpoint: POST https://sqs.eu-west-1.amazonaws.com automatically 

perhaps when you setting a custom endpoint it wont be added automatically to all your queuename..

**Comment by phihag** [comment]
[ex_aws](https://github.com/ex-aws/ex_aws) also sends the requests without a `queue/`. Sure, that may be wrong client behavior, but it would be nice to fix. At least ex_aws can be tricked by prefixing the queue name with `queue/`.

**Comment by prokopyl** [comment]
I've been having this issue, from [ex_aws](https://github.com/ex-aws/ex_aws) as well, and the client behavior is indeed completely wrong (I'll file an issue on their project).

About this subject, [the AWS documentation specifically states](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-general-identifiers.html#queue-name-url):

> In your system, always store the entire queue URL exactly as Amazon SQS returns it to you when you create the queue (for example, https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue). Don't build the queue URL from its separate components each time you need to specify the queue URL in a request because Amazon SQS can change the components that make up the queue URL. 

In short, you should never ever use the queue name in your requests, nor try to rebuild the URL from scratch, but only store and use the exact URL returned by calls to `CreateQueue` and `GetQueueUrl`.

Considering the fact that ElasticMQ returns queue URLs in the form of `http://localhost:<port>/queue/foo`, it is therefore correct, and even necessary to require to include the full path in queries (i.e. the `/queue` part for ElasticMQ specifically).

The only issue with this is that the error message that is returned is incorrect and misleading (it seems to ask for additional parameters when the URL is wrong), especially considering that adding the `QueueName` parameters as asked actually works as a (wrong?) workaround?
I could open other issues for these two problems, but in any case I think this issue can be safely closed.

The only thing I don't understand in all this is why AWS actually accepts malformed Queue URLs, especially considering that the missing part is the IAM user ID.

**Comment by habibqureshi** [comment]
I was facing the same issue on local with elasticMQ, I changed the URL to => `http://localhost:<port>/queue/foo` 
as @prokopyl mentioned, it worked for me as well

**Comment by rojekp** [comment]
@IdanFridman, I checked that issue and I have very same situation. BUT - pay attention for some points:

1) firstly, like AWS doc states here:
 https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html
 One of the parameter of operation `SendMessage` is `queueURL` and from the description:
 `The URL of the Amazon SQS queue to which a message is sent.`
 For now using only queue name works, but in the future - nobody knows.
 
 2) Methods `CreateQueue` and also `GetQueueUrl` return exactly `queueUrl` - which may be used later in your code.
 
 3) ElasticMQ supports even both formats of `queueUrl`:
 - `http://localhost:<port>/queue/<queueName>`
 - `http://localhost:<port>/<accountID>/<queueName>`
 
 4) Returned error message `Invalid request: MissingQueryParamRejection(QueueName)` probably is not very useful here, so feel free to open an issue.
