### ISSUE TITLE
For the standalone version, ReceiveMessageResponse is missing a few attributes

### ISSUE THREAD

**Issue by yuzhangoscar** [softwaremill/elasticmq#127]
SQS.CreateReceiveRequest();
SQS.ReceiveResponse = SQS.Client.ReceiveMessage(SQS.ReceiveRequest);
foreach (var attr in SQS.ReceiveResponse.Messages[0].Attributes)
{
    Console.WriteLine("  " + attr.Key + "  " + attr.Value);
}

I got

- SentTimestamp

- Approx.ReceiveCount

- Approx.FirstReceiveTimestamp

- Senderid

Are not there supposed to be more attributes such as VisibilityTimeout and WaitTimeSeconds?

**Comment by panuhorsmalahti** [comment]
MessageDeduplicationId is also missing.

**Comment by simong** [comment]
@yuzhangoscar:
VisibilityTimeout and WaitTimeSeconds are [parameters for the `ReceiveMessage` request](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) and aren't typically returned in the attributes dictionary. Can you reproducing using a specific queue configuration or with the SQS command line tools?

@panuhorsmalahti: That attribute (along with the `MessageGroupId`) is returned for received messages on FIFO queues. ElasticMQ should support FIFO queues as of 0.14.0 and should be returning both these attributes. :)

**Comment by michalo2882** [comment]
The behavior is as @simong said. I didn't find any more problems, so the issue can be closed.
