### ISSUE TITLE
Ignored attribute "RedrivePolicy"

### ISSUE THREAD

**Issue by carymrobbins** [softwaremill/elasticmq#132]
I'm confused about Dead Letter Queue support. According to this issue https://github.com/adamw/elasticmq/issues/124#issuecomment-370620243 it seems it should work; however, when running elasticmq 0.13.8 (via sbt-sqs) I see this warning when setting the RedrivePolicy -

```
WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Ignored attribute "RedrivePolicy" (supported by SQS but not ElasticMQ)
```

Might I just be doing something wrong?

**Comment by jaxley** [comment]
Looks like the code is set to be part of 0.13.9, which is not yet in the repositories and is only tagged here, but not listed as a release.
