### ISSUE TITLE
Queue config supported in embedded mode

### ISSUE THREAD

**Issue by krisso-b** [softwaremill/elasticmq#133]
While starting embedded server we should be able to provide queue's configuration.
It's already possible to provide such parameter in standalone mode:
```
-Dconfig.file=custom.conf
```

More or less it should look like
```
SQSRestServerBuilder
  .withConfigFile("classpath:/com/company/custom.conf")
  .start();
```

Alternatively/additionally we may consider providing file's content:
```
String config = "queues { ... }"; // normally shouldn't be hardcoded

SQSRestServerBuilder
  .withConfig(config)
  .start();
```

**Comment by TheNickBartlett** [comment]
Been looking for this feature for a while now. Would love to see it happen!

**Comment by michalo2882** [comment]
`SQSRestServerBuilder` does not do any autoconfiguration based on config.
You should used `ElasticMQServer` as described in [README](https://github.com/softwaremill/elasticmq/blob/master/README.md#starting-an-embedded-elasticmq-server-with-an-sqs-interface).
