### ISSUE TITLE
How to provide logback.xml/-Dlogback.configurationFile with the docker distribution?

### ISSUE THREAD

**Issue by ankon** [softwaremill/elasticmq#149]
We've used our own Docker images for a long time, and I looked into replacing these with the "official" images recently added.

The one thing I'm unable to see is how to configure additional java VM properties (`-D`), particularly how to configure the logback configuration. I cannot find the actual Docker images used to look things up myself, and I'm not a sbt person to understand the magic of https://github.com/adamw/elasticmq/commit/8480da6a8dd96726ec084ddf04280bb5343026dc

**Comment by adamw** [comment]
Ah, good point! Definitely this needs to be documented.
There's no explicit docker file, it's generated by sbt. If you try building it locally, everything docker-related will be in `server/target/docker`.

As for your specific question, java options are in the image in the file `opt/docker/conf/application.ini`. The default content is: `-Dconfig.file=/opt/elasticmq.conf`, so you should be able to add logback configuration there if needed. Could you check if this works for you? And is there anything else you'd need from the image?

**Comment by ankon** [comment]
Thanks, I think this should work -- will get back to you after testing this tomorrow!

Right now I don't think we'd need anything else, for reference our dockerfile looks like this right now:
```
FROM openjdk:8-jre-alpine

ARG ELASTICMQ_VERSION
ENV ELASTICMQ_VERSION ${ELASTICMQ_VERSION:-0.13.8}

RUN apk add --no-cache curl ca-certificates
RUN mkdir -p /opt/elasticmq/log /opt/elasticmq/lib /opt/elasticmq/config
RUN curl -sfLo /opt/elasticmq/lib/elasticmq.jar https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-${ELASTICMQ_VERSION}.jar

WORKDIR /opt/elasticmq

EXPOSE 9324

ENTRYPOINT [ "/usr/bin/java", "-jar", "/opt/elasticmq/lib/elasticmq.jar" ]
```

(The actual user of this overwrites the entrypoint to add the `-D` parts for elasticmq.conf and logback.xml, which is fine as we control both the image source and the caller -- I would feel queasy doing this with official images though)

**Comment by cloudson** [comment]
Not sure if I'm looking for the same thing. Is there a way to change logs settings via elasticmq.conf ?

**Comment by ankon** [comment]
Not really. You'd provide a suitable `logback.xml`, and tell the JVM about that one by setting the `logback.configurationFile` system property (`-Dlogback.configurationFile=/path/to/logback.xml`).

**Comment by cloudson** [comment]
Got it. Thank you for the quick answer @ankon . As you are also running it on docker, let me do just one more question.  
I'm running a docker image with command 

```
CMD ["java", "-Djava.net.preferIPv4Stack=true", "-Dconfig.file=/etc/elasticmq/elasticmq.conf", "-jar", "/elasticmq-server.jar"]
```

and I'm not seeing in the logs anything regarding the usage of the queues (received/consumed messages). Is it really something that is out of default settings?

**Comment by ankon** [comment]
I am not sure about the default logging settings, but if it helps: This is our `logback.xml`.

```xml
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
          <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
              <level>INFO</level>
          </filter>
          <encoder>
              <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
          </encoder>
      </appender>

      <root level="INFO">
          <appender-ref ref="STDOUT" />
      </root>
    </configuration>
```

**Comment by Opalo** [comment]
Thanks @ankon for the input. I've updated `README.md` file and added both options to pass `-D` properties: 
- `docker run` along with `-v` switches
- `Dockerfile` from your comment.

Thanks for the valuable input!
