### ISSUE TITLE
can't send message from AWS .net client

### ISSUE THREAD

**Issue by benlucchesi** [softwaremill/elasticmq#150]
I'm trying to send a message using the AWS .Net client, and I'm getting and InvalidParameterException, with an inner exception of 400 Bad Request. Here's a network trace of the HTTP exchange:

POST /queue/queuename_eventBus_azdev.fifo HTTP/1.1
User-Agent: aws-sdk-dotnet-45/3.3.3.16 aws-sdk-dotnet-core/3.3.24.8 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_10.0.17134.0 ClientSync
Content-Type: application/x-www-form-urlencoded; charset=utf-8
host: localhost:9324
X-Amz-Date: 20180823T211155Z
X-Amz-Content-SHA256: 4d95ad3250ad4d4ce1ef0ff585e4c81a96ae855be46408aaf94e8771f74a43ba
Authorization: AWS4-HMAC-SHA256 Credential=fakekey/20180823/us-east-1/sqs/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=c5f68734d5200db333feccba3879a416a9a50dff8e21d2fe99b6f04e7aa75b2
Request-Id: |bOeDmzfHx7o=.fd17ddda_1091.
Content-Length: 639

Action=SendMessage&DelaySeconds=0&MessageBody=(encoded message body omitted)&MessageDeduplicationId=8878665f-f222-4b1b-a669-28563370f629&MessageGroupId=common&Version=2012-11-05HTTP/1.1 400 Bad Request
Server: akka-http/10.1.3
Date: Thu, 23 Aug 2018 21:30:09 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 339

<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
      <Error>
        <Type>Sender</Type>
        <Code>InvalidParameterValue</Code>
        <Message>InvalidParameterValue; see the SQS docs.</Message>
        <Detail/>
      </Error>
      <RequestId>00000000-0000-0000-0000-000000000000</RequestId>
    </ErrorResponse>

Every other request works - list queues, receive messages, etc - and I'm able to send the queue a message from the aws commandline client.

Any help would be appreciated.

**Comment by benlucchesi** [comment]
figures it out... turned out to be an issue with parameter validation not correctly processing parameters. will submit a pull request shortly.

**Comment by mberlanda** [comment]
What is the issue you are facing? I tried it out with Ruby and Java SDK and it works fine. It looks however that the latest release is not working for Node SDK as well https://github.com/localstack/localstack/issues/910

**Comment by adamw** [comment]
@benlucchesi do you know which parameter that is?

**Comment by benlucchesi** [comment]
@mberlanda - the issue is with the AWS .Net client. 

@adamw  - I'm not sure at this point. I was going to figure out which one was offending. As a quick fix, I commented out the parameter validation to get my code working. I'm out of town for the next 10 days and I don't have my primary dev machine, so I won't be able to work on the issue. I do recall that when I compared the send message packets from the java aws-cli vs the .net client in my app, the paths after the POST action were different. the java client posted to / while the .net client posted to /queue/...

**Comment by Opalo** [comment]
@benlucchesi is this problem solved or does it require any work from our side?

**Comment by Opalo** [comment]
@benlucchesi @mberlanda does this issue require any work from our side?

**Comment by Opalo** [comment]
Closing, since OP didn't provide any response.
