### ISSUE TITLE
Akka Timed Out Error

### ISSUE THREAD

**Issue by vammyK** [softwaremill/elasticmq#153]
When I create messages using JMS/SQS
I get following error

akka.actor.ActorSystemImpl - Request timeout encountered for request [POST /queue/queue1 Strict(129 bytes)]
15:58:52.689 [elasticmq-akka.actor.default-dispatcher-20] INFO  akka.actor.DeadLetterActorRef - Message [org.elasticmq.MessageData] from Actor[akka://elasticmq/user/$a/$c#1667985933] to Actor[akka://elasticmq/deadLetters] was not delivered. [9] dead letters encountered. If this is not an expected behavior, then [Actor[akka://elasticmq/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

**Comment by michalbogacz** [comment]
I had this problem too.
The sqs request I sent (with alpakka) has parameter `WaitTimeSeconds=20`. But, before wait time ended, elasticmq http server is timing out request.

It can be resolved with adding `akka.http.server.request-timeout = 40 s` to elasticmq.conf

**Comment by Opalo** [comment]
After creating a queue with:
```
aws sqs --region eu-central-1 --endpoint-url http://localhost:9324 create-queue --queue-name lol
```
And testing message receival with `WaitTimeSeconds` from range (0..21):
```
for i in {0..21}; 
    do
    echo $i; 
    aws sqs --region eu-central-1 --endpoint-url http://localhost:9324 receive-message --queue-url http://localhost:9324/queue/lol --wait-time-seconds $i; 
    done
```
and:
```
for i in {0..21};
    do
    echo $i;
    curl -v --data-binary "Action=ReceiveMessage&WaitTimeSeconds=$i" http://localhost:9324/queue/lol
    done 
```
I've never got an akka timeout in response. It seems that it's working correctly. 

Please mind that, despite you can set `akka.http.server.request-timeout` in [`application.conf`](https://github.com/softwaremill/elasticmq/blob/develop/rest/rest-sqs/src/main/resources/application.conf#L14) the max. value for `WaitTimeSeconds` cannot be higher than 20s - this value is validated [here](https://github.com/softwaremill/elasticmq/blob/develop/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L402).

**Comment by michalbogacz** [comment]
You won't be able to reproduce it unless you would slow down your system (but it's hard to reproduce). In my case, I had many containers open and probably low memory.
Default elasticmq `akka.http.server.request-timeout` is 21s. Many clients have set `WaitTimeSeconds=20`. This means elasticmq has 1 second to send a response. If system resources are very low, it's possible to exceed 21s timeout. 
Anyway increasing `akka.http.server.request-timeout` helped in my case.

**Comment by Opalo** [comment]
@michalbogacz thanks for the clarification. For future readers, remember you're still able to modify `akka.http.server.request-timeout` directly in `application.conf` configuration file.
