### ISSUE TITLE
API returns no error code when requesting non-existing Action

### ISSUE THREAD

**Issue by prokopyl** [softwaremill/elasticmq#171]
When requesting a non-existing Action (or when forgetting to put the field) ElasticMQ currently answers this, with a 404 HTTP status code:

```The requested resource could not be found.```
This result can easily be reproduced with this simple `curl` command:
```curl -v --data-binary "Action=Foobar" http://localhost:9324/queue/foo```

According to the AWS docs (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonErrors.html#CommonErrors-InvalidAction), it should return the `InvalidAction` and `MissingAction` error codes, and with a 400 HTTP status code instead.

Besides not quite adhering to the AWS "specs", this is actually more of an usability issue, as the current message conveys no information about what went wrong.
In my case, I ended up having a typo in my request (`ReceiveMessages` instead of `ReceiveMessage`), and it took me days to figure out what was my mistake, finding what causes this error completely by luck.

**Comment by Opalo** [comment]
@prokopyl how would this request look like if aws cli is used instead of curl?

**Comment by Opalo** [comment]
@prokopyl it's been resolved. You need to wait for a release which, I hope, will happen soon.
