### ISSUE TITLE
docker configuration file breaking changes

### ISSUE THREAD

**Issue by realies** [softwaremill/elasticmq#176]
was there any reason to change
```
`pwd`/custom.conf:/opt/elasticmq.conf
``` 
to
```
`pwd`/custom.conf:/opt/docker/elasticmq.conf
```
?

**Comment by adamw** [comment]
That was my quick fix for another problem from yesterday, sorry! 

Could you verify that it works as intended now?

**Comment by Opalo** [comment]
@realies could you verify please if Adam's fix solves the problem?

**Comment by realies** [comment]
Indeed it does, thanks!
