### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by waisbrot** [softwaremill/elasticmq#24]
Does elasticmq support HTTPS? I'm trying the following configuration and the server only understands me when I make an HTTP connection to 443. Is there a setting I've missed?

``` scala
node-address {
    protocol = https
    host = sqs.us-west-2.amazonaws.com
    port = 443
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 443
    bind-hostname = "0.0.0.0"
    // Possible values: relaxed, strict
    sqs-limits = relaxed
}

spray.can.server.parsing.illegal-header-warnings = off
```

**Comment by samrajexterro** [comment]
@adamw - Its been a decade. Still we don't have SSL support? Any one please confirm.

**Comment by micossow** [comment]
@samrajexterro ElasticMQ is a tool used primarily for testing, so we won't add SSL support and if you need it, you can use a proxy as @adamw suggested 10 years ago ;)
