### ISSUE TITLE
Docker - keep create queue in volume

### ISSUE THREAD

**Issue by kmualem** [softwaremill/elasticmq#242]
Hi guys,

I'm using the the elasticmq in docker-compose and creating the queue programmatically using the AWS SDK.
the problem is that after creating the queue and restarting the docker container, the queue is not preserved. 

Is there an option to configure a volume in order to keep the queue?

Thanks a lot,
Kobi.

**Comment by adamw** [comment]
Unforunately, ElasticMQ is an in-memory queue. There's no persistence.
