### ISSUE TITLE
Dynamic QueueUrl

### ISSUE THREAD

**Issue by christhomas** [softwaremill/elasticmq#247]
It would be really nice if the QueueUrl reflected the region and the external hostname that the queue was created for. Right now I can create a queue for the eu-west-1 region and it'll report localhost as the queue hostname.

I can configure the hostname by setting a custom.conf file with the node-address.host/port set to what I want. But this makes the QueueUrl fixed based on what I started the server with. 

It's my understanding that SQS QueueUrls look like this pattern: 
`sqs-{region}.amazonaws.com/{account}/{name}`

Is there no way on request to check the incoming request and build the queue url based on that rather than a static variable in a config file?

**Comment by pertu** [comment]
> I can configure the hostname by setting a custom.conf file with the node-address.host/port set to what I want.
> But this makes the QueueUrl fixed based on what I started the server with.

If you set `node-address.host = "*"` then the returned queue url will not be "fixed":

```shell
$ curl -XGET 'http://localhost:9324/?Action=GetQueueUrl&QueueName=abc'     
... <QueueUrl>http://localhost:9324/queue/abc</QueueUrl> ...

$ curl -XGET 'http://192.168.12.3:9324/?Action=GetQueueUrl&QueueName=abc'
... <QueueUrl>http://192.168.12.3:9324/queue/abc</QueueUrl> ...
```

It does not save "the external hostname that the queue was created for", only returns the current request's address back.
