### ISSUE TITLE
SendMessage response locks up the AWS .NET SDK

### ISSUE THREAD

**Issue by crhossen** [softwaremill/elasticmq#25]
The SendMessage call returns a "// TODO:" comment in the XML response. This breaks the AWS .NET SDK. 0.8.1 does not have this issue.

The offending file is at rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SendMessageDirectives.scala.

**Comment by YuraDubensky** [comment]
Still reproducable in Release 0.12.0

**Comment by adamw** [comment]
@YuraDubensky same request, same reason? (`TODO`?)
Are you adding any options to `SendMessage` or just a simple verison?

**Comment by YuraDubensky** [comment]
When using AWS .net SDK client just hangs forever when calling AmazonSQSClient.ReceiveMessage method. It doesn't hang when queue is empty, so its all about something wrong with response.

When I call api thought browser I get such response:
Request URL: 
http://localhost:9324/queue/products-local/?Action=ReceiveMessage

Response:
<ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
              <ReceiveMessageResult>
                <Message>
                  <MessageId>27c13f1a-cd32-4991-b40d-b8245dfc67ac</MessageId>
                  <ReceiptHandle>27c13f1a-cd32-4991-b40d-b8245dfc67ac#d0de5f84-e11e-4083-aaf8-9f5f22cf45f5</ReceiptHandle>
                  <MD5OfBody>b1180e3016d082cb9e8f3a355bf22e15</MD5OfBody>
                  <Body>{&quot;$type&quot;:&quot;Partybox.Domain.Commands.UpdateProductIndexCommand, Partybox.Domain.Commands&quot;,&quot;Id&quot;:100005,&quot;Type&quot;:&quot;Reservation&quot;,&quot;CommandType&quot;:&quot;UpdateProductIndex&quot;,&quot;ScheduledTo&quot;:null}</Body>                         <MD5OfMessageAttributes>d41d8cd98f00b204e9800998ecf8427e</MD5OfMessageAttributes> // TODO: Only include if message attributes
                   // TODO: Filter to only requested attributes
                </Message>
              </ReceiveMessageResult>
              <ResponseMetadata>
                <RequestId>00000000-0000-0000-0000-000000000000</RequestId>
              </ResponseMetadata>
            </ReceiveMessageResponse>

So probably those "TODO:x" comments are treated as not valid XML by Amazon.SQS.AmazonSQSClient

**Comment by adamw** [comment]
@YuraDubensky  Should be fixed in 0.12.1

**Comment by YuraDubensky** [comment]
@adamw Works like a charms! Thanks for such a quick response!
