### ISSUE TITLE
Mount directories instead of files in Docker

### ISSUE THREAD

**Issue by mibollma** [softwaremill/elasticmq#301]
Mounting files is only supported on Linux and not portable to other OSs.
This makes it unnecessarily difficult to use this docker image on Windows and other operating systems.
For details take a look at https://github.com/moby/moby/issues/30555.

**Comment by mibollma** [comment]
For anyone struggling with this issue.
To apply a custom configuration on Windows create a custom application.ini
```
application.ini:
-Dconfig.file=/opt/docker/conf/elasticmq.conf
```
Then place the **application.ini** and the configuration file **elasticmq.conf** in the same folder and mount it to **/opt/docker/conf** e.g. with `--mount type=bind,source="$(pwd)"/somefolder,target=/opt/docker/conf`.

**Comment by adamw** [comment]
Thanks! Maybe you could create a PR for the readme which would explain this?
