### ISSUE TITLE
Visibility behaviour does not work when using sdk

### ISSUE THREAD

**Issue by cortopy** [softwaremill/elasticmq#315]
I'm trying to test Visibility in my code, but I can't get elasticMQ to work in the same way as I would expect from AWS.

If we take this example:

```js
    // 1. create queue
    const queue = await sqs.createQueue({ QueueName: 'my-queue' }).promise();

    // 2. send message
    await sqs
      .sendMessage({
        MessageBody: "my message",
        QueueUrl: queue.QueueUrl
      })
      .promise();

    // 3. wait for message to be in queue. It doesn't take this long, but just in case
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    // 4. get message
    const poll1 = await sqs
      .receiveMessage({
        QueueUrl: queue.QueueUrl
      })
      .promise();
    
    // 5. change visibility
    await sqs
      .changeMessageVisibility({
        QueueUrl: queue.QueueUrl,
        ReceiptHandle: poll1.Messages[0].ReceiptHandle,
        VisibilityTimeout: 1
      })
      .promise();
    
    // 6. wait for message to be available again
    await new Promise(resolve => setTimeout(resolve, 1500));
    
   // 7. poll again
    const poll2 = await sqs
      .receiveMessage({
        QueueUrl: queue.QueueUrl
      })
      .promise();

   // poll2 has no messages!!
```

`poll1` contains the message published. However, after changing the Visibility of the message to 1 second, I would expect the message would be available again after the time has elapsed. However, it isn't.

Different variations I've tried generate same result:

- Different visibility times (including using the strategy of `VisibilityTimeout` 0)
- Creating queue with default visibility
```
{
  QueueName: 'new-hires',
  Attributes: {
    DelaySeconds: '0',
    VisibilityTimeout: '1',
   }
}
```
Trying to `getQueueAttributes` returns
```
{
      ResponseMetadata: { RequestId: '00000000-0000-0000-0000-000000000000' }
}
```
so I don't know what's going on this case.
- Different mixes of the three options above

This is all tested using node sdk. I've not tried using the docker config file as I need to create queues on the fly

**Comment by corte** [comment]
@cortopy How did you solve this issue?
I'm having the same. Have a DefaultVisibilityTimeout as 30s and after calling ChangeMessageVisibility to 1s it still waits the 30 seconds to appear again.
