### ISSUE TITLE
delete-message with invalid receipt handle doesn't throw any error

### ISSUE THREAD

**Issue by voleksav** [softwaremill/elasticmq#324]
Assume we have two queues, one is in the AWS and the other resides in the ElasticMQ locally. Both are empty.

When I try to delete the message from the queue in the AWS using the invalid receipt handle, I get the following:
```
aws sqs delete-message --queue-url https://queue.amazonaws.com/real-queue-url --receipt-handle fake

An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessage operation: The input receipt handle "fake" is not a valid receipt handle.
```

And when I try to do the same operation on the local queue in the elasticMQ it performs silently:
```
aws --endpoint-url http://localhost:9324 sqs delete-message --queue-url http://localhost:9324/queue/local_queue --receipt-handle fake
```

I start elasticMQ from Docker container by running `docker run -p 9324:9324 softwaremill/elasticmq` 
The version of the image is `0.15.3`

**Comment by davey91** [comment]
Experiencing the same, it seems that the way sqs works is slightly different than how elasticmq works here. Is there any update on this?

**Comment by adamw** [comment]
@davey91 Unfortunately no, but maybe you'd like to try fixing the problem? If you'd have problems with the codebase, I'll be happy to help

**Comment by davey91** [comment]
Yes, I'd love to have a look! I'm not sure when I'll get around to it though

**Comment by timharsch** [comment]
The problem occurs for me even with a valid receipt handle

    # aws --endpoint-url http://localhost:9324 sqs receive-message --queue-url http://localhost:9324/queue/queue_name --wait-time-seconds 10
    {
        "Messages": [
            {
                "MessageId": "35269736-a1a0-40e2-88eb-05e3ea20a4d1",
                "ReceiptHandle": "35269736-a1a0-40e2-88eb-05e3ea20a4d1#e31bd7cb-e01c-4bb2-b83d-53cd1d95d729",
                "MD5OfBody": "572e90647e0b699a516c19593993ed06",
                "Body": "{ .. a body in JSON format .. }"
            }
        ]
    }
    # aws --endpoint-url http://localhost:9324 sqs delete-message --queue-url http://localhost:9324/queue/queue_name --receipt-handle '35269736-a1a0-40e2-88eb-05e3ea20a4d1#e31bd7cb-e01c-4bb2-b83d-53cd1d95d729'

After executing these commands and going to the Web Console I can see that the message with that ID is still there:
![image](https://user-images.githubusercontent.com/61298249/94181330-2f26c780-fe54-11ea-98c2-20268bccbfb0.png)

I'm using the version of ElasticMq that is include in the docker in dockerhub roribio16/alpine-sqs:1.0.0

**Comment by sashokbg** [comment]
@timharsch I had the same problem and ended up changing the docker image I am using  to the official one **softwaremill/elasticmq** and all problems were solved.

**Comment by timharsch** [comment]
> @timharsch I had the same problem and ended up changing the docker image I am using to the official one **softwaremill/elasticmq** and all problems were solved

Thanks I'll give that a try
