### ISSUE TITLE
Publish softwaremill/elasticmq-native

### ISSUE THREAD

**Issue by mathiswiehl** [softwaremill/elasticmq#325]
Looks like the last versions weren't published for `softwaremill/elasticmq-native`. This is unfortunate since #309 would be nice to have on docker hub.

**Comment by adamw** [comment]
First it would be good to migrate to https://sbt-native-packager.readthedocs.io/en/latest/formats/graalvm-native-image.html :) If somebody would like to take that task ...

**Comment by adamw** [comment]
Done in 0.15.7.
