### ISSUE TITLE
Spring Boot SimpleMessageListenerContainer.stop('queue') takes very long time

### ISSUE THREAD

**Issue by bstoilov** [softwaremill/elasticmq#339]
When testing send-receive flow, I disable the Sqs Listeners for the test.

However the stop method takes very long time, from 5 to 10 seconds.

`simpleMessageListenerContainer.stop("queue-name");`

simpleMessageListenerContainer is autowired

Has anyone else experienced the same behaviour?

**Comment by Jimeh87** [comment]
I don't think this is a elasticmq issue. spring-cloud long polls the maximum amount (20 seconds) by default. If you were to set the wait timeout `simpleMessageListenerContainer#setWaitTimeOut(null)` this should fix your very long stop issue. Alternatively you could set AutoStartup to false so it doesn't start in the first place.

Note you will need to set these properties before simpleMessageListenerContainer#start is called.

**Comment by bstoilov** [comment]
Yes I also came to the same conclusion. But reducing the timeout to values below 6-7 seconds causes timeouts.
Using the AmazonSQS client directly to stop the queue, takes milliseconds, so it seems that spring messaging is lagging for some reason. I opened issue/question on their github as well
https://github.com/spring-cloud/spring-cloud-aws/issues/543

**Comment by Jimeh87** [comment]
as long as the waitTimeout is less than the stop timeout (plus a little room incase there processes running on the message thread) you shouldn't run into timeouts.

It is possible to set the wait time out on a queue instead of as a message attribute. Maybe that's what is causing you issues? by setting waitTimeOut to null it defers to the queues wait timeout.

Try setting `setWaitTimeOut(1)` and `setQueueStopTimeout(3000)`. That's what we have for our tests and we don't run into timeouts.

**Comment by bstoilov** [comment]
I have tried
        simpleMessageListenerContainer.setQueueStopTimeout(3000);
        simpleMessageListenerContainer.setWaitTimeOut(1);
but I still get timeouts
I needed to set the timeout to at least 20000 to avoid timeouts. Not sure what might be causing this. However I testes the same setup with localstack and I still have the same issue so this is not elasticMQ issue for sure.

**Comment by Jimeh87** [comment]
localstack uses elasticMQ under the hood.

**Comment by bstoilov** [comment]
I didn't know that, thanks.

**Comment by sinaarmaghan** [comment]
What helped me on this issue was this post: 
[](https://github.com/spring-attic/spring-cloud-aws/issues/543)

@Bean
SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory() {
	SimpleMessageListenerContainerFactory factory = new SimpleMessageListenerContainerFactory();
	factory.setWaitTimeOut(0);
	return factory;
}
