### ISSUE TITLE
`Successful` and `Failed` missing after calling `sendMessageBatch` with an empty `Entries` array

### ISSUE THREAD

**Issue by davidvuong** [softwaremill/elasticmq#351]
I'm using `elasticmq` to mock out SQS for local development, using the `:latest` docker image.

```
08:13:10.156 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.8) ...
```

Here is some example code:

```ts
const response = await sqsClient.sendMessageBatch({
  QueueUrl: 'xxx',
  Entires: []
}).promise();
```

Gives:

```
{
   ResponseMetadata: { RequestId: '00000000-0000-0000-0000-000000000000' }
}
```

However, passing a non-empty `Entries` array:

```ts
const response = await sqsClient.sendMessageBatch({
  QueueUrl: 'xxx',
  Entires: [{ Id: 'xxx', MessageBody: 'yyy']]
}).promise();
```

Gives:

```ts
{
  ResponseMetadata: { RequestId: '00000000-0000-0000-0000-000000000000' },
  Successful: [
    {
      Id: 'xxx',
      MessageId: '1d51dc22-0a17-43a8-822d-1ab4e2fb9c2a',
      MD5OfMessageBody: 'f0a4058fd33489695d53df156b77c724',
      MD5OfMessageAttributes: 'd41d8cd98f00b204e9800998ecf8427e'
    }
  ],
  Failed: []
}
```

Would it be possible to _always_ return `Successful` and `Failed` even as empty arrays?

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#sendMessageBatch-property

* `Successful — (Array<map>)`
* `Failed — (Array<map>)`

Thanks

**Comment by adamw** [comment]
You seem to have an old verison, can you check the latest one? https://hub.docker.com/r/softwaremill/elasticmq
