### ISSUE TITLE
elasticmq native does not load /opt/elasticmq.conf file

### ISSUE THREAD

**Issue by gabfssilva** [softwaremill/elasticmq#368]
It seems that `elasticmq-native` ignores the ` /opt/elasticmq.conf` file, making it impossible to pre-configure queues before start-up.

**Comment by iStefo** [comment]
We experience the same issue. When starting `elasticmq-native` with the following command, the actual contents of the configuration file (even obvious bogus data) doesn't matter:

```sh
docker run --rm -it --publish 9324:9324 -v /Users/istefo/Development/service_insights/_dev/sqs/elasticmq.conf:/opt/elasticmq.conf softwaremill/elasticmq-native
```

<details><summary>Output FYI</summary>
<pre>
07:27:48.174 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.7) ...
07:27:48.204 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
07:27:48.209 [elasticmq-akka.actor.default-dispatcher-6] INFO  c.t.sslconfig.akka.AkkaSSLConfig - ssl-config.default is true, using the JDK's default SSLContext
07:27:48.210 [elasticmq-akka.actor.default-dispatcher-9] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
07:27:48.211 [elasticmq-akka.actor.default-dispatcher-9] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
07:27:48.212 [elasticmq-akka.actor.default-dispatcher-6] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
07:27:48.212 [elasticmq-akka.actor.default-dispatcher-6] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
07:27:48.213 [elasticmq-akka.actor.default-dispatcher-7] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
07:27:48.219 [elasticmq-akka.actor.default-dispatcher-7] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
07:27:48.219 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.7) started in 46 ms ===
</pre>
</details>

We would really like to use the lightweight (and fast starting) elasticmq-native image, but we need to load pre-created queues from the config file.

**Comment by gabfssilva** [comment]
That's great, @iStefo! Thanks for sharing.
