### ISSUE TITLE
Fifo queue created with a config file does not end with `.fifo` suffix.

### ISSUE THREAD

**Issue by eXtreme** [softwaremill/elasticmq#394]
According to [SQS Docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html) "The name of a FIFO queue must end with the .fifo suffix.". But I cannot make it work with Elasticmq. 

When I define a custom config file `custom.conf` like this:

```
...
queues {
    testfoo {
        fifo = true
        defaultVisibilityTimeout = 5 minutes
        receiveMessageWait = 0 seconds
        contentBasedDeduplication = true
    }
}
...
````

The service starts up. But the queue is named "testfoo", not "testfoo.fifo", even though it is fifo queue. Trying to connect to "testfoo" queue works, but "testfoo.fifo" ends with unknown queue error.

When I try to change the conf file and queue name to "testfoo.fifo" the service does not start. It looks like it treats this conf file as invalid.

The software I use depend on ".fifo" suffix to define if this is a SQS FIFO queue (well, you should be able to rely on that as the docs say "FIFO queue must end with the .fifo suffix."). But I cannot make it work.

I checked the test suite for elasticmq (I don't know much about Scala) and there seems to be a test https://github.com/softwaremill/elasticmq/blob/36cd45c2842588b9b92f63e910b9c81558069324/rest/rest-sqs-testing-amazon-java-sdk/src/test/scala/org/elasticmq/rest/sqs/AmazonJavaSdkTestSuite.scala#L427 for making sure fifo queue ends with ".fifo". And the next test makes queue pragramatically `new CreateQueueRequest("testQueue.fifo")`. And maybe it works when you create the queue with code but I have no way to check that. 

But for me it does not work with a conf file. Am I doing something wrong? Or is it a bug?

**Comment by adamw** [comment]
Fixed in [0.15.8](https://github.com/softwaremill/elasticmq/releases/tag/v0.15.8)
