### ISSUE TITLE
Request `message_attributes` key is filtered out

### ISSUE THREAD

**Issue by conwayje** [softwaremill/elasticmq#418]
From a `worker` instance log, I see this log line:

```
[ActiveJob] [Aws::SQS::Client 200 0.008046 0 retries] send_message(message_body:"{\"job_class\":\"Foo\",\"job_id\":\"someId\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[],\"executions\":0,\"locale\":\"en\"}",message_attributes:{"shoryuken_class"=>{string_value:"ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper",data_type:"String"}},queue_url:"http://alpine-sqs:9324/queue/default")
```

I can confirm (via UI of `alpine-sqs` project) that the message is received, and all keys are stored with full and correct values, *except for* `message_attributes`, which is missing entirely.  In our use case, the `message_attributes` key is required for our ActiveJob processor (`shoryuken`) to identify jobs it should handle.

Apologies if this is not a true issue and there is some configuration I'm simply missing.  I've tried reading through the code and documentation to the best of my ability but didn't see anything that I thought was applicable to ensuring `message_attributes` would be recorded in the queue.  Thanks in advance.

**Comment by michalo2882** [comment]
You need to specify, that you want to receive the message attributes, for example:
`http://localhost:9324/000123006660/queueName1?Action=ReceiveMessage&MessageAttributeName.1=All`
After #448 it will be also possible to use it without the `.N` postfix (some SDKs may generate such requests):
`http://localhost:9324/000123006660/queueName1?Action=ReceiveMessage&MessageAttributeName=All`
