### ISSUE TITLE
GetQueueUrl should return aws account id if set

### ISSUE THREAD

**Issue by leo-form3** [softwaremill/elasticmq#421]
The current GetQueueUrl implementation is not fully compatible with the SQS interface.

The response returns "queue" where the awsAccountId should be.

 ie:
`{protocol}://{host}/queue/{queue_name}`

instead of:
`{protocol}://{host}/{account_id}/{queue_name}`

This is always set to `QueueUrlContext` here: https://github.com/softwaremill/elasticmq/blob/28ef9c95126e3fdca950a6c98df8ed534b0be9e3/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L405

Get Queue Url docs: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html

Happy to work on a PR if there's no reason why this couldn't be changed.

**Comment by wojciechUrbanski** [comment]
Seems like a bug, if You can create a PR we will be happy to review it :)
