### ISSUE TITLE
Wrong artifacts scm on published maven poms

### ISSUE THREAD

**Issue by fernandomora** [softwaremill/elasticmq#430]
According to published POM in https://repo1.maven.org/maven2/org/elasticmq/elasticmq-rest-sqs_2.13/0.15.8/elasticmq-rest-sqs_2.13-0.15.8.pom
```
<scm>
    <url>https://github.com/softwaremill/elasticmq-rest-sqs</url>
    <connection>git@github.com:softwaremill/elasticmq-rest-sqs.git</connection>
</scm>
```

Project source url is on github `softwaremill/elasticmq-rest-sqs` repository
But actual one is `softwaremill/elasticmq`

I think `sbt-softwaremill-publish` is using sbt module name as the github repository name for setting the scm published metadata

**Comment by adamw** [comment]
This was simply not set. Fixed now :)

**Comment by adamw** [comment]
Thanks!
