### ISSUE TITLE
FIFO de-duplication cache not reset on purge

### ISSUE THREAD

**Issue by chris-crowther** [softwaremill/elasticmq#437]
We are using ElasticMQ to simulate an SQS FIFO queue for some automated tests. Our tests purge the queue before each test case. However, it seems that the de-duplication logic persists between purges. Is this intentional? Is there a way to forcibly clear the cached de-duplication IDs?

Version: docker `softwaremill/elasticmq:1.0.0`

**Comment by adamw** [comment]
This might be a bug or a feature - depending on how the "real" SQS works? (I don't know)

A possible work-around could be to start a new elasticmq instance per-test - this might be feasible using the elasticmq-native docker, which starts up much faster. Still, there might be some overhead, but you always get a clean slate.
