### ISSUE TITLE
npm points to older version 0.7.1

### ISSUE THREAD

**Issue by yuklai** [softwaremill/elasticmq#47]
Can you update it, @adamw? Thanks!

**Comment by adamw** [comment]
Sure, though how do I do that? :)

**Comment by yuklai** [comment]
I'm not exactly sure TBH, but I wonder if NPM is pointing to a particular github branch or check-in hash?

**Comment by adamw** [comment]
Is there any way to see who's the author of https://www.npmjs.com/package/elasticmq ? :) I'm not an npm user so I don't really know how exactly things work there :)

**Comment by yuklai** [comment]
I naturally assumed you owned it. :) I guess I should have asked. 
I honestly don't know. It doesn't seem like they have the owner's contact on that page.

**Comment by yuklai** [comment]
I contacted npm, will see if I can find out more and report back.

**Comment by yuklai** [comment]
Turns out I can find out myself.

npm view elasticmq
 
{ name: 'elasticmq',
  description: 'ElasticMQ via NPM (requires Java)',
  'dist-tags': { latest: '0.7.1' },
  versions: '0.7.1',
  maintainers: 'grncdr <glurgle@gmail.com>',
  time: 
   { modified: '2013-09-25T03:47:56.008Z',
     created: '2013-09-25T03:47:53.259Z',
     '0.7.1': '2013-09-25T03:47:56.008Z' },
  author: 'Stephen Sugden <me@stephensugden.com>',
  version: '0.7.1',
  bin: { elasticmq: './wrapper.js' },
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  repository: '',
  files: 
   [ 'README.md',
     'elasticmq-server-0.7.1.jar',
     'wrapper.js',
     'LICENSE.txt' ],
  keywords: [ 'elasticmq', 'sqs' ],
  license: 'Apache License 2.0',
  dist: 
   { shasum: '55379404b09d78611383e41f1aeb8efac2fa2f3e',
     tarball: 'http://registry.npmjs.org/elasticmq/-/elasticmq-0.7.1.tgz' },
  directories: {} }

**Comment by DerekOverlock** [comment]
@adamw any update on this? I'm using elasticmq with my Node.js service and discovered an incompatibility with 0.7.1 (seems to not support QueueUrl in the body). Confirmed that 0.13.2 fixes the issue, would be nice if the npm package contained the newest version. Happy to help out if I can.

**Comment by adamw** [comment]
Thanks, I have no idea what's happening with the npm module or what's the process of updating it :)

**Comment by adamw** [comment]
I think the package is abandoned on npm so there's not much we can do here
