### ISSUE TITLE
Message not delivered to DLQ

### ISSUE THREAD

**Issue by rbraeunlich** [softwaremill/elasticmq#519]
Hi everybody,
I try to write an integration test that checks that my deletionPolicy is correctly configured. I use version `2.13:1.2.0` in an embedded fashion. My configuration looks like this:
```
include classpath("application.conf")

akka.http.server.request-timeout = 40 s

queues {
  retry-queue {
    defaultVisibilityTimeout = 1 seconds
    delay = 500 millis
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "retry-queue-dead-letters"
      maxReceiveCount = 3
    }
    fifo = false
    contentBasedDeduplication = false
  }
  retry-queue-dead-letters {
      defaultVisibilityTimeout = 1 seconds
      delay = 500 millis
      receiveMessageWait = 0 seconds
      fifo = false
  }
}
```
The 40 seconds I took over from an older issue. Nevertheless, after the three retries, I can always see this in the logs:
```
15:10:48.928 [elasticmq-akka.actor.default-dispatcher-11] INFO  akka.actor.DeadLetterActorRef - Message [scala.runtime.BoxedUnit] from Actor[akka://elasticmq/user/$a/$a#1636093795] to Actor[akka://elasticmq/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://elasticmq/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
and when I try to get a message from the DLQ, it's empty. For the sake of completeness, here's the initialization code:
```
        val config = ConfigFactory.load("elasticmq.conf")
        val server = ElasticMQServer(ElasticMQServerConfig(config))
        val shutdown = server.start()
```
Does anybody know what's going wrong?

**Comment by TrejGun** [comment]
Hey guys I have the same problem but it is not consistent. 

here is my repo https://github.com/GemunIon/nestjs-sqs

in one terminal run
```sh
java -Dconfig.file=.github/build/elasticmq.conf -jar elasticmq-server-1.2.0.jar
```

in another
```
npm i
npm t
```

as I said it is not consistent so you may have to execute `npm t` several times

**Comment by pierscin** [comment]
@rbraeunlich  I wouldn’t worry about that log - it is as intended and it happens because of [this line](https://github.com/softwaremill/elasticmq/blob/15b177227f6553bc626e7e299ce6836d87a35e7e/core/src/main/scala/org/elasticmq/actor/queue/operations/ReceiveMessageOps.scala#L63). Message is copied to DLQ and it is removed from previous processing.

I don’t know why did you have an empty DLQ though 🤔  . You send something to Q, then you acquire it more times than `maxReceiveCount` (taking into account visibility timeouts), and then message will be transferred to DLQ (log from `DeadLetterActorRef` happens around this time). After it is transferred there, it will stay until it is removed or server is restarted. You can look up statistics of all queues on port `9325` - maybe this will help.
If your code produces a lot of moving to DLQ and logs are annoying, you could silence them in logback (if you use it). I believe that this entry will do the job.
<logger name="akka.actor.DeadLetterActorRef" level="WARNING" />
Below is code I used for testing - maybe you will see something of use for you:
```scala
package elasticmq

import com.amazonaws.auth.{AWSStaticCredentialsProvider, BasicAWSCredentials}
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration
import com.amazonaws.services.sqs.AmazonSQSClientBuilder
import com.amazonaws.services.sqs.model.{Message, ReceiveMessageRequest, SendMessageRequest}
import scala.jdk.CollectionConverters._

object ExampleClient {
  val host = "http://localhost:9324"
  val qurl = host + "/queue/retry-queue"
  val dlqurl = host + "/queue/retry-queue-dead-letters"

  val client = AmazonSQSClientBuilder
    .standard()
    .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("x", "x")))
    .withEndpointConfiguration(new EndpointConfiguration(host, "us-east-1"))
    .build()


  def getOneMessage(queueUrl: String): Message = {
    client
      .receiveMessage(new ReceiveMessageRequest(queueUrl)
        .withWaitTimeSeconds(2)
        .withAttributeNames("All"))
      .getMessages
      .asScala
      .headOption
      .orNull
  }

  def main(args: Array[String]): Unit = {

    println(s"Qs available: ${client.listQueues()}")
    println()
    val req = new SendMessageRequest(qurl, s"Message 1")
    //      .withMessageGroupId("1") //when fifo = true
    //      .withMessageDeduplicationId("DedupId") //when dedup = true

    client.sendMessage(req)
    val visibilityTimeoutInMillis = 1000

    println("Receiving messages from Q")
    for { i <- 1 to 5 } {
      println("i = " + i)
      Thread.sleep(visibilityTimeoutInMillis + 100)
      println(client.receiveMessage(qurl))
    }

    println("Receiving messages from DLQ")
    for { i <- 1 to 5 } {
      println("i = " + i)
      Thread.sleep(visibilityTimeoutInMillis + 100)
      println(client.receiveMessage(dlqurl))
    }
  }
}
```

**Comment by pierscin** [comment]
@TrejGun I don’t know type script, but I will share my insights - test passes when it is ran on clean server or if we wait at least 10s (visibility timeout). Other than that your last test fails. I don’t see any message in q statistics. Is your code producing and removing message immediately from q?

**Comment by TrejGun** [comment]
@pierscin yes you are right 10 seconds timeout works

**Comment by adamw** [comment]
@TrejGun so is your issue resolved?

**Comment by TrejGun** [comment]
yes, thanks

**Comment by rbraeunlich** [comment]
Hey @pierscin 
thank you for the example and the explanation. I managed to get my test running. Looks like it was a misconfiguration in the Docker container wrapping the ElasticMQ server.
