### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by GadgetGeekUK** [softwaremill/elasticmq#525]
When trying to publish to an elasticmq queue using the AWSSDK (.net Core), the call eventually times out and returns: 'nodename nor servname provided, or not known'. Any ideas what it is exactly asking for, it doesn't seem to match any config options?

**Comment by adamw** [comment]
Can you post some example code to reproduce the problem?

**Comment by micossow** [comment]
If you still have this issue and are able to provide an example please reopen.
