### ISSUE TITLE
[Feature request] UI for seeing all messages through the system

### ISSUE THREAD

**Issue by kennydude** [softwaremill/elasticmq#56]
I think it would be useful to be able to have a web UI to view all of the messages in the queue, kind of like how the AWS console works but preferably can just stream them on the page without peeking into the queues

**Comment by pc-omikheev** [comment]
Or at least JMX MBeans with some stats, because currently log is the only means of getting traffic stats as far as I understand

**Comment by FreifeldRoyi** [comment]
+1
Is it part of ElasticMQ roadmap in the near future?

**Comment by adamw** [comment]
Released in 1.0.0! :)

**Comment by iautom8things** [comment]
@adamw What is the endpoint to view these messages?  I'm using the latest version from docker hub (https://hub.docker.com/r/softwaremill/elasticmq-native/tags) which looks to be 1.4.5 but there's no link on the admin dashboard to view the messages.  I just see a table of the queues that gives total number of messages and queue attributes.  There does not seem to be a way to view the actual messages.

**Comment by micossow** [comment]
@iautom8things ElasticMQ UI does not support looking up messages' contents and we're not planning to add this functionality.
