### ISSUE TITLE
Debug Endpoints

### ISSUE THREAD

**Issue by charlie-cho-carbon** [softwaremill/elasticmq#566]
Hello, 

While http://localhost:9325/ is a great debug feature to see the queue details, but I was wondering if there easy curable endpoints (without having to deal w/ aws features) to enqueue objects, or flush a queue. 
Sorry if this question is redundant. 
Really appreciate this project!

**Comment by micossow** [comment]
@charlie-cho-carbon unfortunately the UI bundled with ElasticMQ is limited to displaying queue metadata and stats.
You can check out this project https://github.com/roribio/alpine-sqs which uses ElasticMQ inside.
