### ISSUE TITLE
Is it possible to set up elasticmq to trigger a consumer lambda function locally when it has messages?

### ISSUE THREAD

**Issue by gabsong** [softwaremill/elasticmq#571]
Hello,

I was able to use elasticmq to simulate a producer lambda function sending messages into the queue. Now, I want to configure elasticmq to trigger a consumer lambda function (as it works in AWS). Is this possible to do?

**Comment by adamw** [comment]
ElasticMQ only implements the Amazon SQS interface. For more components, such as lambda, take a look at https://github.com/localstack/localstack
