### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by KacperFKorban** [softwaremill/elasticmq#637]
Are there plans for Scala 3 support?

**Comment by adamw** [comment]
For sure, once akka-http has a Scala 3 release :)

**Comment by kirillsalykin** [comment]
Is akka-http for scala 3 gonna be ever released? any chance to use something different?

**Comment by adamw** [comment]
I think we'll have to switch to a different server, there will be an akka-http for Scala 3 release but not under an open-source license
