### ISSUE TITLE
Messages are not moved to DLQ when the DLQ name contains underscores

### ISSUE THREAD

**Issue by Stanleyyyan** [softwaremill/elasticmq#673]
We observed some weird behaviors with the DLQ's name containing underscores. When the ReceiveCount for a message exceeds the maxReceiveCount for a queue, the message is deleted from the main queue (the consumer doesn't remove the message from the main queue) and not moved to DLQ as expected.

To reproduce the issue, try configuring a DLQ with the name of "dlq_some_queue".

**Comment by Pask423** [comment]
Just one question, how do you create your queues?

**Comment by micossow** [comment]
@Stanleyyyan can you check if the issue still occurs with `1.3.7`?

**Comment by Stanleyyyan** [comment]
@Pask423, we ran the stand-alone via docker ([link](https://github.com/softwaremill/elasticmq#elasticmq-via-docker))

@micossow, Yes, it's working now!  Thanks for fixing that!
