### ISSUE TITLE
Support for Redrive Policy/dead letter queues

### ISSUE THREAD

**Issue by f24-gklein** [softwaremill/elasticmq#69]
Hi! 
First of all: Thanks for this amazing work!

It would be nice if elasticmq had support for sqs redrive policy and dead letter queues, e.g. in the following places:
- getQueueAttributes
- setQueueAttributes
- also add support for setting 'maxReceiveCount' and 'deadLetterTargetArn' via elasticmq queue configuration file. 
- Correct dead letter queue configuration should be implemented in the 'business logic'  accordingly

See aws doc at: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html

Regards, Gunther

**Comment by travishumphreys** [comment]
Seconded! Especially because I'm trying to testing a queue with redrive policy, and create queue will return QueueNameExists after queue is created because attributes don't match.

**Comment by norcalli** [comment]
Thirded, so that we could match our production server in testing.

**Comment by AjayTripathy** [comment]
Was this resolved in https://github.com/adamw/elasticmq/pull/91 , or is only static configuration via the conf file supported for now?

**Comment by adamw** [comment]
@AjayTripathy DLQs are only supported when creating queues (either via the API or static config). Adding support for get/set attribute should be an easy change, though

**Comment by seanf** [comment]
I think this can be closed now. DLQs can now be created via setAttribute too (#147).

It appears that a message won't be moved to the DLQ until a client tries to receive it again (after exceeding `maxReceiveCount`). I'm not sure if that's standard SQS behaviour.

**Comment by Opalo** [comment]
Thanks @seanf - closing then :)
