### ISSUE TITLE
Disable to restore persisted FIFO queue config

### ISSUE THREAD

**Issue by kamegu** [softwaremill/elasticmq#697]
Hi

When using `queues-storage` config and creating FIFO queue, the queue is correctly created.
But when restarted, persisted queues does not be restored.

---

started with config
``` elasticmq.conf
include classpath("application.conf")

queues-storage {
  enabled = true
  path = "/data/queues.conf"
}
```
and created FIFO queue
```
aws sqs create-queue --queue-name dummy.fifo --attributes ReceiveMessageWaitTimeSeconds=20,FifoQueue=true --endpoint-url http://localhost:9324
```
then, file `/data/queues.conf` is created
```
queues {
 dummy.fifo {contentBasedDeduplication=false,copyTo="",defaultVisibilityTimeout=30000,delay=0,fifo=true,moveTo="",receiveMessageWait=0,tags{}}
}
```

In this config file, name includes `.fifo` suffix.
TypeSafe Config may read incorrectly as follows.
```
queues {
 dummy {
  fifo {contentBasedDeduplication=false,copyTo="",defaultVisibilityTimeout=30000,delay=0,fifo=true,moveTo="",receiveMessageWait=0,tags{}}
 }
}
```

**Comment by micossow** [comment]
Hi @kamegu, I did some cleanup in #702 and had to change the behavior you have proposed as it was not consistent with how we handle queue creation. As suggested in https://github.com/softwaremill/elasticmq/issues/125#issuecomment-1180431751 you should escape your fifo queue name and that's how the conf generator works now. For example:
```
queues {
 "queue-123_test" {contentBasedDeduplication=false,copyTo="",defaultVisibilityTimeout=30000,delay=0,fifo=false,moveTo="",receiveMessageWait=0,tags{}}
 "queue-123_test.fifo" {contentBasedDeduplication=false,copyTo="",defaultVisibilityTimeout=30000,delay=0,fifo=true,moveTo="",receiveMessageWait=0,tags{}}
}
```
