### ISSUE TITLE
add native arm image

### ISSUE THREAD

**Issue by realies** [softwaremill/elasticmq#724]
currently, it seems like elasticmq-native runs through qemu-x86_64 on arm, could this be made into a native image? it would really benefit laptop development and battery life, since it currently takes about 10-20% cpu with a light polling client

**Comment by micossow** [comment]
Continuation of #473

**Comment by realies** [comment]
thanks @micossow, as I mentioned there, there's darwin aarch64 support over at https://github.com/graalvm/graalvm-ce-dev-builds/releases now, could m1 arm native elasticmq-native images be a thing with it?

**Comment by micossow** [comment]
It should be possible to build such image now, see: https://github.com/sbt/sbt-native-packager/issues/1503
Some changes in build.sbt are probably also necessary.

**Comment by fvasco** [comment]
I tested the image `softwaremill/elasticmq-native:1.3.14` on a Graviton AWS server, but it does not work

~~~
# docker run softwaremill/elasticmq-native:1.3.14
Unable to find image 'softwaremill/elasticmq-native:1.3.14' locally
1.3.14: Pulling from softwaremill/elasticmq-native
Digest: sha256:c251751b5d668033c69494ff37a938f977397ad3c806085e53f269bedb2c3ead
Status: Downloaded newer image for softwaremill/elasticmq-native:1.3.14
[FATAL tini (7)] exec /opt/docker/bin/elasticmq-native-server failed: Exec format error
~~~

The executable in the image is in amd64 format

~~~
file opt/docker/bin/elasticmq-native-server
opt/docker/bin/elasticmq-native-server: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=2ad8fd7fe117da1b01aea2b469d54497c42743d3, with debug_info, not stripped, too many notes (256)
~~~

Other files look for aarch64 architecture.

**Comment by kderholtvisma** [comment]
Will this be fixed? or is there a quick way of building this from the repo manually?

**Comment by micossow** [comment]
If you need docker image locally, you can run `sbt "project nativeServer; clean; assembly; graalvm-native-image:packageBin; docker:publishLocal"` on your AMR64 system.

To be able to create native docker images as a part of GH workflow, we need either:
* GH Workflow supporting ARM64 systems
* or cross compilation support in GraalVM https://github.com/oracle/graal/issues/407

**Comment by diegobfernandez** [comment]
[GitHub released](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) a MacOS builder which is M1 based.
Could that be used for ARM64 builds?

**Comment by adamw** [comment]
@diegobfernandez Interesting - if we only use it for releases, it might not be that expensive (hopefully in the order of a couple of dollars)

**Comment by micossow** [comment]
Hello, I updated build.sbt to use buildx supported image creation, which should create proper native images for both x64 and ARM. Please test if `softwaremill/elasticmq-native:1.4.5-RC1` image works on your ARM machines. If yes, I'll create a release next week.

**Comment by micossow** [comment]
Update: `softwaremill/elasticmq-native:1.4.5-RC2` has a fix for UI.

**Comment by micossow** [comment]
Fixed in https://github.com/softwaremill/elasticmq/releases/tag/v1.4.6
