### ISSUE TITLE
Each Queue's DelaySeconds parameter is always set to 0 when enabling queues-storage and reloading from a persisted queues config file.

### ISSUE THREAD

**Issue by rich-baker-clearskyconcepts** [softwaremill/elasticmq#728]
Using the serverless-offline-sqs plugin along with Elasticmq running in a Docker container, and the serverless-offline-sqs plugin configured to autoCreate the Queues.

One of the Queues defined in the resources section of serverless.yml has a DelaySeconds parameter set to 600.

When first starting everything up, all Queues get auto-created as expected (verifiable via the Elasticmq Web UI and via its auto-generated persisted queues config file), and the DelaySeconds for the one Queue is correctly set to 600.

Upon stopping and restarting the Elasticmq container (forcing it to reload from its persisted queues config file), the one Queue's DelaySeconds parameter is now set to 0.  This is verifiable via the Elasticmq Web UI and via the persisted queues config file.

This issue is occurring in both the softwaremill/elasticmq-native and softwaremill/elasticmq container images.

**Comment by micossow** [comment]
Hi, thanks for reporting the issue. It's fixed in `v1.3.11`
