### ISSUE TITLE
Configured queues not created in v0.9.3

### ISSUE THREAD

**Issue by sam-lewis** [softwaremill/elasticmq#73]
I have configured queues by adding `custom.conf` as specified in the README but the queue is not created because I get the error: `com.amazonaws.services.sqs.model.QueueDoesNotExistException: AWS.SimpleQueueService.NonExistentQueue`

I have created a small example reproducing my issue here: https://github.com/sam-lewis/elastic-mq-test

San you help?

**Comment by adamw** [comment]
if you are starting ElasticMQ from Java try naming the file `application.conf` - it should then get picked without any system properties.

**Comment by sam-lewis** [comment]
I [applied the changes](https://github.com/sam-lewis/elastic-mq-test/commit/656c46d5fb393923d24870b0fea814cebc21cbe6) but the queue is still not created.

**Comment by adamw** [comment]
Ok, sorry I read the code and now I know what's going on; your previous version with `custom.conf` was ok, however the queues are created by the `server` module, not the `rest-sqs` which you are using.

If you add a dependency on `elastimq-server`, and start it like here: https://github.com/adamw/elasticmq/blob/master/server/src/main/scala/org/elasticmq/server/Main.scala#L16, the queues should be created

**Comment by tehmaestro** [comment]
Hi, I am unable to create a queue on startup. I'm using a super simple config file taken from readme. I did not understand exactly what I should to from the post above. Could you give a little more details? Thank you so much!

**Comment by adamw** [comment]
@tehmaestro Are you using the latest version? Are you calling the `GetQueueUrl` method to obtain the address of a named queue?

**Comment by tehmaestro** [comment]
Yes. I'm using the following command to start elasticmq
`java -Dconfig.file=custom.conf -jar elasticmq-server-0.13.8.jar`

```
include classpath("application.conf")

queues {
    my-queue {
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
    }
}
```

However, on startup, my-queue does not exist.

**Comment by tehmaestro** [comment]
I updated the config to use a dead letter queue too, and everything seems to be working now. I don't know if using the dead letter queue changed something and made it working, or that had nothing to do with it, and it simply started working after I restart my PC.

**Comment by adamw** [comment]
Probably out of date
