### ISSUE TITLE
Race condition in CreateQueue causes it to throw QueueAlreadyExists when it should be a noop

### ISSUE THREAD

**Issue by tolmasky** [softwaremill/elasticmq#747]
According to the [SQS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html), if you call `CreateQueue` with the same name and attributes as a previously call to `CreateQueue`, you should just get back the same URL as the previous one:

> If you provide the name of an existing queue along with the exact names and values of all the queue's attributes, CreateQueue returns the queue URL for the existing queue.

You only get a queue already exists error if you attempt to `CreateQueue` with the same name but different attributes:

> If the queue name, attribute names, or attribute values don't match an existing queue, CreateQueue returns an error.

This is generally the case with the elasticmq implementation, *except* if you happen to have two calls to `CreateQueue` happen close enough to each other that the first one isn't "complete" yet. In that circumstance, I believe `LookupQueue` returns `None`:

https://github.com/softwaremill/elasticmq/blob/71db7607b460bba3bbb39640ee3364bfa2a6b3ec/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/CreateQueueDirectives.scala#L124-L127

Which causes the code to go into the `CreateQueueMsg` path:

https://github.com/softwaremill/elasticmq/blob/71db7607b460bba3bbb39640ee3364bfa2a6b3ec/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/CreateQueueDirectives.scala#L130-L131

And thus end up in QueueManagerActor's `CreateQueue` call which then fails because it finds a pre-existing ActorRef for a queue with the same name (but notably, doesn't bother checking the associated attributes of said in-flight queue creation request) and thus throws a `QueueAlreadyExists` error:

https://github.com/softwaremill/elasticmq/blob/78d5842ceca7275028887155cbfb4466d4eade84/core/src/main/scala/org/elasticmq/actor/QueueManagerActor.scala#L20-L25

This is hitting us since we start a cluster of processes that create queues (some of which are identical), and depending on the timing of these requests, sometimes it works fine (if they happen to be spaced far enough apart), but other times fails. This is not on issue with AWS SQS.

I believe the correct behavior should be that if there is an existing `ActorRef` for a queue with the same name *and* same attributes, it should simply wait on that one and return the same response as that one. The same as would happen if the request had just happened a little later.

**Comment by micossow** [comment]
Thanks for reporting the issue. It's fixed in `1.3.12`
