### ISSUE TITLE
why do you use SQS

### ISSUE THREAD

**Issue by HoangNgo88** [softwaremill/elasticmq#789]
Hi, I am reading your project and I love this project
I have a question, why do you choose SQS in your project instead of others like RabbitMQ or Kafka, are there any special features but others dont have it. Can you share me it. I am wondering when I should choose SQS instead of others like RabbitMQ or Kafka

**Comment by adamw** [comment]
I think the following might provide good answers:
https://stackoverflow.com/questions/28687295/sqs-vs-rabbitmq
https://softwaremill.com/mqperf/
https://stackoverflow.com/questions/42151544/when-to-use-rabbitmq-over-kafka
