### ISSUE TITLE
CreateQueueRequest fails for fifo queue

### ISSUE THREAD

**Issue by atanasTsekov** [softwaremill/elasticmq#790]
Hi,

I am unable to create fifo queue with the following command:

CreateQueueRequest createQueueRequest = new CreateQueueRequest().withQueueName("test-example.fifo").addAttributesEntry("ReceiveMessageWaitTimeSeconds", "20").
                    addAttributesEntry("FifoQueue", "true").addAttributesEntry("ContentBasedDeduplication","true");

Tried to execute the same code against AWS and the queue was successfully created, but when using elasticmq something goes wrong...
Version that I tried using - name: 'elasticmq-rest-sqs_2.11', version: 1.3.9
Error:

com.amazonaws.services.sqs.model.AmazonSQSException: InvalidParameterValue; see the SQS docs. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)

**Comment by micossow** [comment]
Hi, can you include the logs from the application? I can't reproduce it with that CreateQueueRequest

**Comment by atanasTsekov** [comment]
Hi, I tried to reproduce the error but this time the problem is gone and the queue was created. Turns out it was sync problem with my IDE and changing the elasticmq version did not take effect until I reloaded the project. Thank you for your time and I am very sorry for the false alarm :( . Keep up the good work!
