### ISSUE TITLE
MessageTimers (DelaySeconds) with long polling (WaitTimeSeconds)

### ISSUE THREAD

**Issue by igorsechyn** [softwaremill/elasticmq#80]
I am using [message timers ](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-timers.html) to delay the delivery of the message and [long polling ](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html)to reduce the number of calls to SQS. Currently the `WaitTimeSeconds` is set to 10 seconds and the `DelaySeconds` for each message to 2 seconds. The message is however not being delivered after 2 seconds, but rather after the long polling period of 10 seconds. I have confirmed that this behaves as expected when using Amazon SQS. Is there a configuration flag that I might be missing? 

Thanks, Igor.

**Comment by adamw** [comment]
So this works in "real" SQS = messages are delivered after 2 seconds, while in ElasticMQ they are delivered when?

Can you maybe share some code which demonstrates this?

**Comment by igorsechyn** [comment]
Yeah sorry I should have provided more details. I am using JavaScript SDK. This is the code to send messages:

```
            defaultQueue.sendMessage(
                {
                    MessageBody: JSON.stringify(message),
                    QueueUrl: defaultQueueUrl,
                    DelaySeconds: 2
                },
                (error, result) => {
                    logger.info(`Sent message ${message.body.handlerName} at ${new Date()}`);
                    if (error) {
                        reject(error);
                    } else {
                        resolve(result);
                    }
                }
            );
```
And this the code to receive messages:
```
    const params = {
        QueueUrl: defaultQueueUrl,
        AttributeNames: [ATTR_RECEIVE_COUNT],
        MaxNumberOfMessages: 1,
        WaitTimeSeconds: 10
    };

    return new Promise((resolve, reject) => {
        defaultQueue.receiveMessage(params, (error, data) => {
            if (error) {
                reject(error);
            } else {
                logger.info(`Received messages ${JSON.stringify(data.Messages)} at ${new Date()}`);
                const messages = data.Messages || [];
                resolve(messages);
            }
        });
    });
```
Using elastic mq this code produces following logs:
```
Sent message POLL_FOR_RESULT_HANDLER at Wed Sep 28 2016 23:10:31 GMT+0000 (UTC)
Received messages undefined at Wed Sep 28 2016 23:10:41 GMT+0000 (UTC)
Received messages [{...,"Body":"{\"body\":{\"handlerName\":\"POLL_FOR_RESULT_HANDLER\",}”….] at Wed Sep 28 2016 23:10:41 GMT+0000 (UTC)
```
With the real sqs, I get:
```
Sent message POLL_FOR_RESULT_HANDLER at Thu Sep 29 2016 00:30:16 GMT+0000 (UTC)
Received messages [{…."Body\":\"{\\\"body\\\":{"handlerName\\\":\\\"POLL_FOR_RESULT_HANDLER\\\”}…}] at Thu Sep 29 2016 00:30:18 GMT+0000 (UTC)
```

**Comment by adamw** [comment]
I amended one of the existing tests to check that scenario and it passes:
https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs-testing-amazon-java-sdk/src/test/scala/org/elasticmq/rest/sqs/AmazonJavaSdkTestSuite.scala#L817-L831

Are you using the latest ElasticMQ version?
There's also a mysterious `undefined` message at `23:10:41` - maybe you can try logging the raw content (without JSON parsing) to see what it is?

Also, the server should write DEBUG-level logs such as:

```
08:23:58.547 [elasticmq-akka.actor.default-dispatcher-3] DEBUG org.elasticmq.actor.queue.QueueActor - testQueue1: Sent message 
08:23:58.579 [elasticmq-akka.actor.default-dispatcher-3] DEBUG org.elasticmq.actor.queue.QueueActor - testQueue1: Awaiting messages: start for sequence 0.
08:24:00.572 [elasticmq-akka.actor.default-dispatcher-3] DEBUG org.elasticmq.actor.queue.QueueActor - testQueue1: Receiving message d082e833-82ea-4804-b80e-a15d4899dce3
08:24:00.572 [elasticmq-akka.actor.default-dispatcher-3] DEBUG org.elasticmq.actor.queue.QueueActor - testQueue1: Awaiting messages: replying to sequence 0 with 1 messages.
```

which have exact timestamps of actions. Could you check that with your test?

**Comment by adamw** [comment]
Probably out of date
