### ISSUE TITLE
Containers are unable to download jar from s3

### ISSUE THREAD

**Issue by nitesh0420** [softwaremill/elasticmq#801]
Hi I have been facing this issue from last 1 month. Test container startup randomly starts failing. On debugging I found out that the it's not able to download the elasticmq jar within specified time. I even increased the timeout to 20 minutes and still it's not able to download. I debugged and tried to manually download the jar from s3 and it's taking more than 30 minutes. It doesn't happen always but it happens randomly. And it's very annoying when this happens. I tried from different ISP's and still it didn't work. Can someone please help in fixing the issue? This is the s3 url I am facing issue with - https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.1.0.jar

**Comment by micossow** [comment]
Uber jar will be also published to GH release artifacts starting from the next release. See #1015
