### ISSUE TITLE
Calculate MD5 of message system attributes

### ISSUE THREAD

**Issue by katlasik** [softwaremill/elasticmq#827]
Calculate MD5 of message system attributes similarly as message attributes are calculated.

Currently we [always return null](https://github.com/softwaremill/elasticmq/blob/d31bdf2a4fb8be00ab5cbc343f2083641f563ba6/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SendMessageBatchDirectives.scala#L35).

This should be implemented both for sending single message and batch.

**Comment by micossow** [comment]
fixed in [v1.4.2](https://github.com/softwaremill/elasticmq/releases/tag/v1.4.2)
