### ISSUE TITLE
Unable to download jar file

### ISSUE THREAD

**Issue by ameem-chronograph** [softwaremill/elasticmq#853]
I am attempting to add the jar from https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.3.9.jar in my container and it is consistently failing. It appears to be an issue with the server itself as I'm not able to download it manually either.

**Comment by adamw** [comment]
Seems to work fine here. Where are you from? The file is hosted on Amazon S3, can you access e.g. the main AWS website at https://aws.amazon.com ?

**Comment by ameem-chronograph** [comment]
Thanks for the reply @adamw . I'm located on the east coast of the US. I am able to access the main AWS website (and https://s3-eu-west-1.amazonaws.com) as well. The issue is only with downloading this specific file.

**Comment by adamw** [comment]
can you try wget? here's my output:

```
[~]% wget https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.3.9.jar
--2023-07-27 20:43:25--  https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.3.9.jar
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.116.136, 52.218.121.24, 52.218.104.162, ...
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.116.136|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41924727 (40M) [application/octet-stream]
Saving to: ‘elasticmq-server-1.3.9.jar’

elasticmq-server-1.3.9.jar                            100%[=======================================================================================================================>]  39,98M  10,8MB/s    in 4,0s
```

**Comment by ameem-chronograph** [comment]
Here's my output:
```
➜  ~ wget https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.3.9.jar
--2023-07-27 15:14:54--  https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-1.3.9.jar
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.90.11, 52.92.17.104, 52.218.97.43, ...
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.90.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41924727 (40M) [application/octet-stream]
Saving to: ‘elasticmq-server-1.3.9.jar’

elasticmq-server-1.3.9.jar                                1%[>                                                                                                                            ]
 517.31K  --.-KB/s    eta 12h 21m
```
The download is essentially stuck at this point (eta ~13 hours). Perhaps there is an issue is with my location being far away from the bucket, but I wouldn't expect it to be _this_ slow.

**Comment by ameem-chronograph** [comment]
For what it's worth, I do see someone had posted a similar issue before: https://github.com/softwaremill/elasticmq/issues/801

**Comment by micossow** [comment]
It seems like your issue is similar to the one described here: https://www.snellman.net/blog/archive/2017-07-20-s3-mystery/
and unfortunately there's nothing we can do about it.
In future releases we'll add alternative download options for uber jar, see https://github.com/softwaremill/elasticmq/issues/855
As a workaround I'd suggest to use maven/gradle/sbt for your project and including ElasticMQ dependency: https://mvnrepository.com/artifact/org.elasticmq/elasticmq-server_2.13/1.4.2

**Comment by ameem-chronograph** [comment]
Thanks for taking a look. At the moment, I am no longer experiencing the issue and was able to run my container. I'll close this out.
