### ISSUE TITLE
Stale Documentation for DeadLetterQueue creation

### ISSUE THREAD

**Issue by DeeWBee** [softwaremill/elasticmq#865]
I am attempting to create a series of queues with attached DLQs (dead letter queues). I'm specifically referencing the example [provided in the ReadMe](https://github.com/softwaremill/elasticmq#automatically-creating-queues-on-startup). 

If I include `deadLettersQueue` property inside my custom config, no queues are created (indicating something is broken). If I _remove_ the `deadLettersQueue` property, my queues are successfully created.

**This tells me the documentation for custom configs is outdated or incorrect.** Does anyone have updated or functional examples of custom configurations involving DLQs? Attached below is a snippet of my custom configuration. To clarify, I am creating/starting my queues using the Docker image and pointing at a custom `elasticmq.conf` config. 

```
queues {
  SE-Order-SeCommerceApi-v1 {
    defaultVisibilityTimeout = 10 seconds
    delay = 5 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "SE-Order-SeCommerceApi-DLQ"
      maxRecieveCount = 3
    }
    fifo = false
    contentBasedDeduplication = false
  }
  SE-Order-SeCommerceApi-DLQ { }

  SE-CommerceApi-LineItemFulfillment-v1 {
    defaultVisibilityTimeout = 10 seconds
    delay = 5 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "SE-CommerceApi-LineItemFulfillment-DLQ"
      maxRecieveCount = 3
    }
    fifo = false
    contentBasedDeduplication = false
  }
  SE-CommerceApi-LineItemFulfillment-DLQ { }
}
```

**Comment by micossow** [comment]
You have typo in your config: `maxRecieveCount` => `maxReceiveCount`
I added some logging, so that next time you'll see an actual error in the logs:
https://github.com/softwaremill/elasticmq/pull/866

**Comment by DeeWBee** [comment]
@micossow Well that's embarrassing. I really appreciate the quick response and review. 

I'll be sure to better review my own code next time 😬
