### ISSUE TITLE
Migrate from akka to pekko?

### ISSUE THREAD

**Issue by truongnmt** [softwaremill/elasticmq#891]
## Why
As the license for Akka has changed, we are migrating akka to Pekko.

In the test, we have a logic to create a SQS server, but the class `SQSRestServerBuilder` has dependencies on Akka.
https://github.com/softwaremill/elasticmq/blob/5fea28b41b4fc88f8621c09661a8e0831864eded/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L3-L7

Can we consider migrating dependency to Pekko? Thank you very much!

**Comment by adamw** [comment]
Yes, let's do this :) Do you think you'd be able to work on a PR?

**Comment by truongnmt** [comment]
Sure! I will happy to send one in the next few day! ^^

**Comment by truongnmt** [comment]
@adamw 
Send a PR in https://github.com/softwaremill/elasticmq/pull/895. Can you help to check later when you are available? Thank you!

**Comment by micossow** [comment]
@truongnmt I merged your PR however I need to run couple manual tests for native image before the release.

**Comment by truongnm-pp** [comment]
@micossow 
Understood! Thanks for sharing with me.

**Comment by micossow** [comment]
The change has been released in `1.5.0`. Thanks for contribution!
