### ISSUE TITLE
Trigger Events Based on Messages in Queue

### ISSUE THREAD

**Issue by richardgetz** [softwaremill/elasticmq#941]
Is there any way currently, or a plan to add a way, to mimic SQS events to pass a message directly to a script similar to how SQS events work in AWS?

**Comment by micossow** [comment]
I'm not quite sure what you are referring to. AWS Lambda perhaps?

**Comment by richardgetz** [comment]
Yea if I were deploying to AWS and was using SQS and a Lambda I could set an event that would trigger the Lambda based on messages in the queue. Of course I can create a script that just checks the queue periodically, but is there a way to instead do this on the ElasticMQ side to better mimic message events locally?
________________________________

**Comment by micossow** [comment]
Then the answer would be no. This project is simple in-memory queue with SQS API interface.
If you need to test integration of two or more AWS components you can take a look at https://github.com/localstack/localstack project

**Comment by richardgetz** [comment]
Fair enough. Thanks!
