### ISSUE TITLE
404s after updating AWS SDKs

### ISSUE THREAD

**Issue by OliverTaggart** [softwaremill/elasticmq#986]
After upgrading our project's `aws-java-sdk`s from 1.12.565 to 1.12.638 we're seeing the following error with elasticmq queues:
`Exception happened when try to receive messages from queue - com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 404; Error Code: null; Request ID: null; Proxy: null) 09:28:24 user ERROR c.l.u.s.p.<OurProcessor> 525588613033092391 Failed to receive message from queue: http://localhost:9324/queue/<our-queue>+ Cause: null (Service: AmazonSQS; Status Code: 404; Error Code: null; Request ID: null; Proxy: null)`

Upgrading our version of elasticmq to 1.4.2 (we're currently on 0.13.10 :skull: ) doesn't solve the issue, either.  I'm wondering if there's some dependency I need to add to our project, or some other obvious gotcha that I'm missing.  The last time anyone touched our elasticmq implementation was 6 years ago.

We manage our elasticmq version via a chef cookbook, and manage our dependencies with maven.

**Comment by OliverTaggart** [comment]
I should have left a comment when closing (and I maybe closed the issue as something other than 'not planned').  Our issue was the elasticmq upgrade wasn't being applied properly.  After successfully upgrading and applying the latest version of elasticmq, we no longer experienced the issue.  I'll leave it to @micossow to re-close or investigate as needed.

**Comment by kirangubbi** [comment]
Thanks for the updates. I tried iupgrading aws-java-sdks to1.12.750 and elasticmq-rest-sqs to 1.6.5 but it failed with the same 404 error. We need to upgrade aws-java-sdks to at least 1.12.638 which has fixes of OWASP high vulnerability (dependent library ion-java-1.0.2). Please provide what version of aws-java-sdks and elasticmq-rest-sqs fixed this 404 error.

**Comment by micossow** [comment]
@kirangubbi are you using the latest version w ElasticMQ? The latest version is tested against SDK `1.12.699`. If you have any issues with the latest version, I would need more details to reproduce the issue.

**Comment by kirangubbi** [comment]
Thanks for the updates. I tried upgrading aws-java-sdks to1.12.750 and elasticmq-rest-sqs to 1.6.5 but failed with the some date format issue. Then I changed elasticmq-rest-sqs to 1.5.3. It worked.

**Comment by kirangubbi** [comment]
I am not entirely sure if it relates to ElasticMQ. I just went for 1.5.3 because after that version it has additional support for scala 3 which I thought might be causing this issue.

**Comment by micossow** [comment]
Ok, I'll close the issue then.
